format_version: 2
pipelines:
  demo-pipeline:
    group: todolist
    materials:
      git-repo:
        git: https://github.com/WasinWatt/vue-gotham-todo.git
        branch: master
    stages:
      - first-stage:
          jobs:
            list:
              tasks:
                - exec:
                    command: ls
                    arguments:
                      - .
      - second-stage:
          jobs:
            cat-readme:
              tasks:
                - exec:
                    command: cat
                    arguments:
                      - README.md