format_version: 2
pipelines:
  pipeline-name:
    group: group-name
    materials:
      git-repo:
        git: https://github.com/WasinWatt/vue-gotham-todo.git
        branch: master
    stages:
      - first-stage:
          jobs:
            list:
              tasks:
                - exec:
                    command: cd
                    arguments:
                      - vue-gotham-todo
                - exec:
                    command: npm
                    arguments:
                      - install
                - exec:
                    command: npm
                    arguments:
                      - run
                      - test
                - exec:
                    command: npm
                    arguments:
                      - lint
                - exec:
                    command: ./gotham-todo/build.sh
                - exec:
                    command: ./gotham-todo/apply-infrastructure.sh
                - exec:
                    command: ./gotham-todo/copy-static-files.sh