format_version: 2
pipelines:
  todo-list:
    group: todo-list-group
    materials:
      git-repo:
        git: https://github.com/gotham-learning/vue-gotham-todo.git
        branch: master
    stages:
      - install-and-build:
          jobs:
            install-and-build:
              artifacts:
                - build:
                    source: gotham-todo/dist
              tasks:
                - exec:
                    command: ./gotham-todo/install.sh
                - exec:
                    command: ./gotham-todo/test.sh
                - exec:
                    command: ./gotham-todo/build.sh
      - deploy:
          jobs:
            deploy:
              tasks:
                - fetch:
                    pipeline: todo-list
                    stage: install-and-build
                    job: install-and-build
                    source: gotham-todo/dist/
                    is_file: no
                    destination: gotham-todo/
                - exec:
                    command: ./gotham-todo/apply-infrastructure.sh
                - exec:
                    command: ./gotham-todo/copy-static-files.sh